version: '2'
services:
  lnd:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    user: '10000'
    labels:
      lagoon.type: lnd
      lagoon.persistent: /app/storage
    environment:
      LAGOON_LOCALDEV_HTTP_PORT: 8080
      LAGOON_ROUTE: http://lnd.docker.amazee.io
    volumes:
      - ./storage:/app/storage:delegated
    env_file:
      - .env.local
    ports:
      - "8080" # exposes the port 8080 with a random local port, find it with `docker-compose port lnd 8080`
      - "10009" # exposes the port 10009 with a random local port, find it with `docker-compose port lnd 10009`

  thunderhub:
    networks:
      - amazeeio-network
      - default
    build:
      context: thunderhub
      dockerfile: Dockerfile
    user: '10000'
    environment:
      LOG_LEVEL: silly
      LAGOON_LOCALDEV_HTTP_PORT: 3000
      LAGOON_ROUTE: http://thunderhub.docker.amazee.io
    volumes:
      - ./storage:/data:delegated
    labels:
      lagoon.type: thunderhub
      lagoon.persistent: /data
      lagoon.persistent.name: lnd
    ports:
      - "3000" # exposes the port 3000 with a random local port, find it with `docker-compose port thunderhub 3000`
    env_file:
      - .env.local

  tor:
    networks:
      - amazeeio-network
      - default
    build:
      context: tor
      dockerfile: Dockerfile
    user: '10000'
    labels:
      lagoon.type: lnd
      lagoon.autogeneratedroute: false
    ports:
      - "9050"
      - "9051"
networks:
  amazeeio-network:
    external: true

