backupsEnabled: false
accounts:
  - name: ${LND_ALIAS}
    serverUrl: boltup:10009
    macaroonPath: /data/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon
    certificatePath: /data/lnd/tls.cert
    password: ${LND_WALLETPASSWORD}
    network: ${BITCOIN_NETWORK}
