#!/bin/bash

CHECK=`curl --socks5 localhost:9050 --socks5-hostname localhost:9050 -s https://check.torproject.org/ | cat | grep -m 1 Congratulations`

if [ -z "$CHECK" ]; then
  echo "Tor does not seem to be working"
  exit 255
else
  echo "Tor seems to be working"
  exit 0
fi
